### ISSUE TITLE
Instrumenter Timber.Integrations.PhoenixInstrumenter.phoenix_controller_render/3 failed

### ISSUE THREAD

**Issue by tlvenn** [timberio/timber-elixir#237]
Root issue being `(KeyError) key :phoenix_controller not found`

I believe the issue comes from the PhoenixInstrumenter expecting a controller while if it's within Absinthe there is simply none.

```
14:09:49.656 request_id=gcgbmq7vc1b2p02fr1prsn777r169uo0 [error] Instrumenter Timber.Integrations.PhoenixInstrumenter.phoenix_controller_render/3 failed.
** (KeyError) key :phoenix_controller not found in: %{JumpnWeb.Router => {[], %{Absinthe.Plug.GraphiQL => []}}, :absinthe => %{context: %{auth_info: %Jumpn.AuthInfo{remote_ip: {127, 0, 0, 1}, token_serial: "xxxxxx", user_id: 1111111}}}, :phoenix_endpoint => JumpnWeb.Endpoint, :phoenix_format => "json", :phoenix_layout => false, :phoenix_pipelines => [:graphql], :phoenix_recycled => true, :phoenix_router => JumpnWeb.Router, :phoenix_template => "500.json", :phoenix_view => JumpnWeb.ErrorView, :plug_skip_csrf_protection => true, :timber_opts => [], :timber_timer => -576460749737610000}
    (phoenix) lib/phoenix/controller.ex:241: Phoenix.Controller.controller_module/1
    (timber) lib/timber/integrations/phoenix_instrumenter.ex:327: Timber.Integrations.PhoenixInstrumenter.phoenix_controller_render/3
    (jumpn) lib/jumpn_web/endpoint.ex:1: JumpnWeb.Endpoint.instrument/4
    (phoenix) lib/phoenix/controller.ex:740: Phoenix.Controller.do_render/4
    (phoenix) lib/phoenix/endpoint/render_errors.ex:60: Phoenix.Endpoint.RenderErrors.__catch__/5
    (phoenix) lib/phoenix/test/conn_test.ex:224: Phoenix.ConnTest.dispatch/5
    (jumpn) test/support/conn_case.ex:77: Jumpn.ConnCase.post_gql/2
    test/jumpn/user/user_schema_test.exs:498: Jumpn.UserSchemaTest."test childRegister returns a child"/1
    (ex_unit) lib/ex_unit/runner.ex:292: ExUnit.Runner.exec_test/1
    (stdlib) timer.erl:166: :timer.tc/1
    (ex_unit) lib/ex_unit/runner.ex:240: anonymous fn/3 in ExUnit.Runner.spawn_test/3

14:09:49.661 request_id=gcgbmq7vc1b2p02fr1prsn777r169uo0 [error] Instrumenter Timber.Integrations.PhoenixInstrumenter.phoenix_controller_render/3 failed.
** (FunctionClauseError) no function clause matching in Timber.Integrations.PhoenixInstrumenter.phoenix_controller_render/3
    (timber) lib/timber/integrations/phoenix_instrumenter.ex:324: Timber.Integrations.PhoenixInstrumenter.phoenix_controller_render(:stop, 17000, :ok)
    (jumpn) lib/jumpn_web/endpoint.ex:1: JumpnWeb.Endpoint."-instrument/4-after$^3/0-0-"/2
    (jumpn) lib/jumpn_web/endpoint.ex:1: JumpnWeb.Endpoint.instrument/4
    (phoenix) lib/phoenix/controller.ex:740: Phoenix.Controller.do_render/4
    (phoenix) lib/phoenix/endpoint/render_errors.ex:60: Phoenix.Endpoint.RenderErrors.__catch__/5
    (phoenix) lib/phoenix/test/conn_test.ex:224: Phoenix.ConnTest.dispatch/5
    (jumpn) test/support/conn_case.ex:77: Jumpn.ConnCase.post_gql/2
    test/jumpn/user/user_schema_test.exs:498: Jumpn.UserSchemaTest."test childRegister returns a child"/1
    (ex_unit) lib/ex_unit/runner.ex:292: ExUnit.Runner.exec_test/1
    (stdlib) timer.erl:166: :timer.tc/1
    (ex_unit) lib/ex_unit/runner.ex:240: anonymous fn/3 in ExUnit.Runner.spawn_test/3
```

**Comment by erikreedstrom** [comment]
We're using absinthe without issue, but do find that the above occurs when `Plug.Exception` raises for a bad route.

**Comment by tlvenn** [comment]
That is happening during a test hitting absinthe endpoint directly so there is indeed no controller and if the code raise then this issue appears because it tries to lookup for `:phoenix_controller` which cannot be resolved.

**Comment by DavidAntaramian** [comment]
@tlvenn Could you please provide the versions of `timber` and `phoenix` that you're using? This may have been solved with #230. The fix for that is in versions 2.5.6+ and 2.6.0+

**Comment by DavidAntaramian** [comment]
@erikreedstrom Could you please open the `Plug.Exception` problem as a new issue with details about the versions of `absinthe`, `plug`, and `timber` that you have? Thanks

**Comment by erikreedstrom** [comment]
@DavidAntaramian, will do on Monday.
