### ISSUE TITLE
Internal Server Error while setting up 

### ISSUE THREAD

**Issue by samaksh-vokal** [timberio/timber-elixir#302]
Uh oh! We got a bad response (500) from https://api.timber.io/installer/application.
The response received was:

{"errors":[{"message":"Internal server error"}]}

Stacktrace:
```    lib/mix/tasks/timber/install/api.ex:118: Mix.Tasks.Timber.Install.API.request!/4
    lib/mix/tasks/timber/install/application.ex:16: Mix.Tasks.Timber.Install.Application.new!/1
    lib/mix/tasks/timber/install.ex:45: Mix.Tasks.Timber.Install.run/1
    (mix) lib/mix/task.ex:314: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:80: Mix.CLI.run_task/2
    (elixir) src/elixir_compiler.erl:85: :elixir_compiler.dispatch/6
    (elixir) src/elixir_lexical.erl:18: :elixir_lexical.run/3
    (elixir) src/elixir_compiler.erl:27: :elixir_compiler.quoted/3
```

P.S. Tested on new elixir project

**Comment by samaksh-vokal** [comment]
Solved it! Platform was incorrect, and updating platform did not help. Created new app with the correct platform and it worked.
