### ISSUE TITLE
Support Advanced Handling of `:error_logger` messaging

### ISSUE THREAD

**Issue by DavidAntaramian** [timberio/timber-elixir#94]
In the latest version of the library we are dropping handling of `:error_logger` messaging to support issues where the `:ranch` library is not dispatch error messages in a standard manner; we instead are decoding messages as they are sent translated by `Elixir.Logger`. This has necessary tradeoffs. While it allows us to capture errors from `:ranch`, it limits our ability to rebuild contextual documents that were bound to processes since the data is stripped during processing. 

Based on conversations in the Elixir slack #general channel with James Fish and others, utilizing an `:error_logger` GenEvent handler is still the best option for us, but we can improve the way we have handled messages. Work is currently being done on the [rollbax package](https://hex.pm/packages/rollbax) in elixir-addicts/rollbax#62 and is scheduled for the [sentry package](https://hex.pm/packages/sentry) in getsentry/sentry-elixir#117 that improve the handling of `:error_logger` messages by parsing them at a more granular level. Having a similar parsing methodology for Timber is the end goal of this issue.

**Comment by tlvenn** [comment]
Guys, are we still on track to deliver this in April ?

**Comment by DavidAntaramian** [comment]
@tlvenn Thanks for the ping. The work was already merged into master, and we've just prepared a new release containing the feature as 2.8.0. Please let us know if you have any problems by opening an issue!

**Comment by tlvenn** [comment]
Awesome ! Thanks guys.

**Comment by ksheurs** [comment]
How exactly do we get the new error logger integration configured? Do we just need to update to 2.8.0? Thanks!

**Comment by tlvenn** [comment]
@ksheurs in 2 steps:

First, you need to make sure default otp_report handling is disabled in the logger config as follow:

```
config :logger,
  level: :info,
  compile_time_purge_level: :info,
  handle_otp_reports: false,
  backends: [Timber.LoggerBackends.HTTP]
```

Then you simply need to activate OTP report handling with Timber:

```
config :timber,
  capture_error: true,

**Comment by mitchellhenke** [comment]
@tlvenn @ksheurs I unfortunately did not update the documentation accordingly, and there is a step missing. I have opened a PR to update it here: https://github.com/timberio/timber-elixir/pull/273/files

As a quick note, the changes to install it should end up looking something like this (though the linked documentation has some caveats if you're in an umbrella app):

  ```elixir
  # Enable Timber's error capturing system
  config :timber, :capture_errors, true

  # Disable Elixir's default error capturing system
  config :logger, :handle_otp_reports, false
  ```

  ```diff
  def start(_type, _opts) do
    children = [
      supervisor(MyApp.Repo, []),
      supervisor(MyAppWeb.Endpoint, [])
    ]

    opts = [strategy: :one_for_one, name: MyApp.Supervisor]

+ :ok = :error_logger.add_report_handler(Timber.Integrations.ErrorLogger)

    Supervisor.start_link(children, opts)
  end
  ```

**Comment by ksheurs** [comment]
Hi @mitchellhenke, kindly following up on the above. Any ideas on expected behavior with our implementation? Thanks!

**Comment by mitchellhenke** [comment]
@ksheurs yep, you will need to update to 2.8.0

@ConnorMacKenzie You aren't missing any additional setup, but the difference can be difficult to understand (and I may have under-explained it in the documentation).

Using `Timber.Integrations.ErrorLogger` allows for more structured capture of error stacktraces in some cases where a process crashes (Task, GenServer, or similar). It does this by replacing Elixir's [Logger.ErrorHandler](https://github.com/elixir-lang/elixir/blob/master/lib/logger/lib/logger/error_handler.ex). That core Elixir module is responsible for translating events from Erlang's [error_logger](http://erlang.org/doc/man/error_logger.html) and turning it into `Logger` output. By default, events like process crashes that come from `error_logger` end up getting logged as a friendlier string, looking something like:

```
2018-05-03T19:33:29.042647+00:00 app[web.1]: GenServer Testing.GenServer terminating
2018-05-03T19:33:29.042651+00:00 app[web.1]: ** (ArithmeticError) bad argument in arithmetic expression
2018-05-03T19:33:29.042653+00:00 app[web.1]:     (testing) lib/gen_server.ex:36: Testing.GenServer.handle_info/2
2018-05-03T19:33:29.042655+00:00 app[web.1]:     (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
2018-05-03T19:33:29.042657+00:00 app[web.1]:     (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
2018-05-03T19:33:29.042659+00:00 app[web.1]:     (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
2018-05-03T19:33:29.042661+00:00 app[web.1]: Last message: :division
```

That is good, but it would be neat to have the module and stacktrace information as Logger metadata, which is what `Timber.Integrations.ErrorLogger` seeks to do.

With the Timber integration, the log looks like this:

```
2018-05-03T19:33:29.042647+00:00 app[web.1]: GenServer Testing.GenServer terminating
2018-05-03T19:33:29.042651+00:00 app[web.1]: ** (ArithmeticError) bad argument in arithmetic expression
2018-05-03T19:33:29.042653+00:00 app[web.1]:     (testing) lib/gen_server.ex:36: Testing.GenServer.handle_info/2
2018-05-03T19:33:29.042655+00:00 app[web.1]:     (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
2018-05-03T19:33:29.042657+00:00 app[web.1]:     (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
2018-05-03T19:33:29.042659+00:00 app[web.1]:     (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
2018-05-03T19:33:29.042661+00:00 app[web.1]: Last message: :division @metadata {"level":"error","event":{"error":{"name":"ArithmeticError","message":"bad argument in arithmetic expression","backtrace":[{"line":36,"function":"Testing.GenServer.handle_info/2","file":"lib/gen_server.ex"},{"line":616,"function":":gen_server.try_dispatch/4","file":"gen_server.erl"},{"line":686,"function":":gen_server.handle_msg/6","file":"gen_server.erl"},{"line":247,"function":":proc_lib.init_p_do_apply/3","file":"proc_lib.erl"}]}},"dt":"2018-05-03T19:33:29.029603Z","context":{"system":{"pid":4,"hostname":"84fe8ac5-1734-4ce4-af36-4e685f158d71"},"runtime":{"vm_pid":"<0.193.0>"}},"$schema":"https://raw.githubusercontent.com/timberio/log-event-json-schema/v3.1.1/schema.json"}
```

And the right sidebar on Timber will have the stacktrace in a structured, readable format:
![image](https://user-images.githubusercontent.com/1430443/39598769-49d456d2-4edf-11e8-9691-c52d7eb73664.png)

This would be difficult to do without `Timber.Integrations.ErrorLogger`, and it opens up some cool possibilities with the metadata having that information.
